# Generated by Django 3.0.6 on 2020-05-21 10:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200521_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
